let penCost=10;
let pencilCost=20;
//let sum= "the total price :"+ (penCost+pencilCost)+ "rupee";
let output=`the total price : ${penCost + pencilCost} rupees.`; 
console.log(output);
let a=20;
let b=10;
console.log(a+b);
console.log(a-b);
console.log(a%b);
console.log(a*b);
console.log(a/b);
let num=5;
let str='23';
